config/routes.rb
Rails.application.routes.draw do
  namespace :backoffice do
  get 'dashboard/index'
  end

  resources :entries
  resources :category_entries
  resources :kind_entries
  resources :partners
  resources :addresses
  resources :addresses
  resources :phones
  resources :clients
  resources :kinds

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :category_entry
  belongs_to :client



end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private




    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:description, :date_entry, :amount, :category_entry_id, :client_id)
    end


end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :date_entry %><br>
    <%= f.date_select :date_entry %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :category_entry_id %><br>
    <%= f.text_field :category_entry_id %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.text_field :client_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Entries</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Date entry</th>
      <th>Amount</th>
      <th>Category entry</th>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%total_amount = 0.00%> #ver se dá pra declarar no model
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.description %></td>
        <td><%= entry.date_entry %></td>
        <td><%= entry.amount %></td>
        <td><%= entry.category_entry %></td>
        <td><%= entry.client %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% total_amount = entry.amount + total_amount %>
    <% end %>
  </tbody>
</table>
<br>
<%= total_amount %>
<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @entry.description %>
</p>

<p>
  <strong>Date entry:</strong>
  <%= @entry.date_entry %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @entry.amount %>
</p>

<p>
  <strong>Category entry:</strong>
  <%= @entry.category_entry %>
</p>

<p>
  <strong>Client:</strong>
  <%= @entry.client %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>