config/routes.rb
Rails.application.routes.draw do
  namespace :backoffice do
  get 'dashboard/index'
  end

  resources :entries
  resources :category_entries
  resources :kind_entries
  resources :partners
  resources :addresses
  resources :addresses
  resources :phones
  resources :clients
  resources :kinds

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :kind
  has_many   :phones
  has_many   :partners
  has_one    :address
  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :phones, reject_if: :all_blank,allow_destroy: true 

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.order(:codDesc).page(params[:page]).per(15)
    
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
    @client.build_address
    options_for_select
  end

  # GET /clients/1/edit
  def edit
    options_for_select
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    #Define uma coleção para o model kind
    def options_for_select
      @kind_options_for_select = Kind.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:codDesc, :name, :brand, :CNAE, :email, :site, :capital, :kind_id, address_attributes:[:street,:city,:state], phones_attributes:[:id,:prefix,:number,:kind,:_destroy])
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<div class="basic-grey">
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codDesc %><br>
    <%= f.number_field :codDesc %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :CNAE %><br>
    <%= f.number_field :CNAE %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :site %><br>
    <%= f.text_field :site %>
  </div>
  <div class="field">
    <%= f.label :capital %><br>
    <%= f.text_field :capital %>
  </div>
  <div class="field">
    <%= f.label :kind_id %><br>
    <%= collection_select(:client,:kind_id,@kind_options_for_select,:id,:description) %>
  </div>

  <%= f.fields_for :address do |address_fields| %>
   <div class="field">
     <%=address_fields.label :street %><br>
     <%= address_fields.text_field :street,size:70 %>
   </div>
   <div class="field">
     <%= address_fields.label :city %><br>
     <%= address_fields.text_field :city %></div>
   <div class="field">
     <%= address_fields.label :state %><br>
     <%= address_fields.text_field :state %></div>
  <% end %>

     <div id="phones">
       Phones:<br>
       <%= link_to_add_association('Adicionar telefone',f,:phones,'data-association-insertion-method' => 'after') %>

       <%= f.fields_for :phones do |phones_fields| %>
          <%= render partial: 'phone_fields', locals: { f: phones_fields } %>
     </div>

  <% end %>





  <div class="actions">
    <%= f.submit "Enviar", class:"button"  %>
  </div>
<% end %>
</div>

app/views/clients/_phone_fields.html.erb
<div class="nested-fields">

    <div class="field">
        <%= f.text_field :prefix, class:'phone-prefix' %> - <%= f.text_field :number, class:'phone-number'%> - <%= f.text_field :kind,class:'phone-number' %> (<%= link_to_remove_association('Remover',f)%>)
    </div>


</div>

app/views/clients/edit.html.erb
<div class="edit-fields">
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>
</div>

app/views/clients/index.html.erb
<div class="basic-grey">
  <p id="notice"><%= notice %></p>

  <h1>Listing Clients</h1>
<div class="index">
  <table>
    <thead>
      <tr>
        <th>Coddesc</th>
        <th>Name</th>
        <th>Brand</th>
        <th>Kind</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @clients.each do |client| %>
        <tr style="background:<%= cycle('#FFF','#E1EEF4') %>">
          <td><%= client.codDesc %></td>
          <td><%= client.name %></td>
          <td><%= client.brand.capitalize %></td>
          <td><%= client.kind.abbr %></td>
          <td><%= link_to 'Show', client %></td>
          <td><%= link_to 'Edit', edit_client_path(client) %></td>
          <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br><%= paginate @clients%>
</div>
  <br>
</div>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<div class="edit-fields">
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>
</div>

app/views/clients/show.html.erb
<div class="basic-grey">
<p id="notice"><%= notice %></p>
<div class="show-fields">
<p>
  <strong>Coddesc:</strong>
  <%= @client.codDesc %>
</p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @client.brand %>
</p>

<p>
  <strong>Cnae:</strong>
  <%= @client.CNAE %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Site:</strong>
  <%= @client.site %>
</p>

<p>
  <strong>Capital:</strong>
  <%= @client.capital %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @client.kind.abbr %> - <%= @client.kind.description %>
</p>
</div>
<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>
</div>