config/routes.rb
Rails.application.routes.draw do
  namespace :backoffice do
  get 'dashboard/index'
  end

  resources :entries
  resources :category_entries
  resources :kind_entries
  resources :partners
  resources :addresses
  resources :addresses
  resources :phones
  resources :clients
  resources :kinds

end

app/models/category_entry.rb
class CategoryEntry < ActiveRecord::Base
  belongs_to :kind_entry
  belongs_to :category_entry
end

app/controllers/category_entries_controller.rb
class CategoryEntriesController < ApplicationController
  before_action :set_category_entry, only: [:show, :edit, :update, :destroy]

  # GET /category_entries
  # GET /category_entries.json
  def index
    @category_entries = CategoryEntry.all
  end

  # GET /category_entries/1
  # GET /category_entries/1.json
  def show
  end

  # GET /category_entries/new
  def new
    @category_entry = CategoryEntry.new
  end

  # GET /category_entries/1/edit
  def edit
  end

  # POST /category_entries
  # POST /category_entries.json
  def create
    @category_entry = CategoryEntry.new(category_entry_params)

    respond_to do |format|
      if @category_entry.save
        format.html { redirect_to @category_entry, notice: 'Category entry was successfully created.' }
        format.json { render :show, status: :created, location: @category_entry }
      else
        format.html { render :new }
        format.json { render json: @category_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /category_entries/1
  # PATCH/PUT /category_entries/1.json
  def update
    respond_to do |format|
      if @category_entry.update(category_entry_params)
        format.html { redirect_to @category_entry, notice: 'Category entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @category_entry }
      else
        format.html { render :edit }
        format.json { render json: @category_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /category_entries/1
  # DELETE /category_entries/1.json
  def destroy
    @category_entry.destroy
    respond_to do |format|
      format.html { redirect_to category_entries_url, notice: 'Category entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category_entry
      @category_entry = CategoryEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_entry_params
      params.require(:category_entry).permit(:name, :kind_entry_id, :category_entry_id)
    end
end

app/helpers/category_entries_helper.rb
module CategoryEntriesHelper
end

app/views/category_entries/_form.html.erb
<%= form_for(@category_entry) do |f| %>
  <% if @category_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category_entry.errors.count, "error") %> prohibited this category_entry from being saved:</h2>

      <ul>
      <% @category_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :kind_entry_id %><br>
    <%= f.text_field :kind_entry_id %>
  </div>
  <div class="field">
    <%= f.label :category_entry_id %><br>
    <%= f.text_field :category_entry_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/category_entries/edit.html.erb
<h1>Editing Category Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @category_entry %> |
<%= link_to 'Back', category_entries_path %>

app/views/category_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Category Entries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Kind entry</th>
      <th>Category entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @category_entries.each do |category_entry| %>
      <tr>
        <td><%= category_entry.name %></td>
        <td><%= category_entry.kind_entry %></td>
        <td><%= category_entry.category_entry %></td>
        <td><%= link_to 'Show', category_entry %></td>
        <td><%= link_to 'Edit', edit_category_entry_path(category_entry) %></td>
        <td><%= link_to 'Destroy', category_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category entry', new_category_entry_path %>

app/views/category_entries/new.html.erb
<h1>New Category Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', category_entries_path %>

app/views/category_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category_entry.name %>
</p>

<p>
  <strong>Kind entry:</strong>
  <%= @category_entry.kind_entry %>
</p>

<p>
  <strong>Category entry:</strong>
  <%= @category_entry.category_entry %>
</p>

<%= link_to 'Edit', edit_category_entry_path(@category_entry) %> |
<%= link_to 'Back', category_entries_path %>